# Module: orchestrator-stepfunctions
# Serverless orchestration via a Step Functions state machine + a least-privilege role.
# The caller passes the state-machine definition and the task role ARNs it may invoke.

variable "name_prefix" {
  type = string
}

variable "tags" {
  type    = map(string)
  default = {}
}

variable "definition_json" {
  type        = string
  default     = ""
  description = "Amazon States Language JSON for the workflow. If empty, a starter workflow that runs the wired Glue jobs is generated."
}

variable "glue_job_names" {
  type        = list(string)
  default     = []
  description = "Glue job names to orchestrate. Used to generate the starter workflow when definition_json is empty."
}

variable "task_role_arns" {
  type        = list(string)
  default     = []
  description = "Resource ARNs the state machine may act on (e.g. Glue job ARNs)."
}

locals {
  # A real, runnable starter workflow: run the wired Glue jobs sequentially. The operator
  # can replace it by passing an explicit definition_json. Not a mock — it references the
  # actual job names wired from the compute module.
  #
  # Null-filtering matters: merge()-ing {Next} XOR {End} branches makes Terraform unify
  # the object types across the for-expression, emitting "Next": null / "End": null —
  # which the Step Functions CreateStateMachine schema validation rejects.
  generated_states = {
    for idx, name in var.glue_job_names : "Run_${idx}" => {
      for k, v in {
        Type       = "Task"
        Resource   = "arn:aws:states:::glue:startJobRun.sync"
        Parameters = { JobName = name }
        Next       = idx + 1 < length(var.glue_job_names) ? "Run_${idx + 1}" : null
        End        = idx + 1 < length(var.glue_job_names) ? null : true
      } : k => v if v != null
    }
  }
  effective_definition = var.definition_json != "" ? var.definition_json : jsonencode({
    Comment = "Starter workflow generated by MinusOps — runs the wired Glue ETL jobs in sequence."
    StartAt = length(var.glue_job_names) > 0 ? "Run_0" : "NoOp"
    States = merge(
      local.generated_states,
      {
        for k, v in { NoOp = { Type = "Pass", End = true } } : k => v
        if length(var.glue_job_names) == 0
      }
    )
  })
}

data "aws_iam_policy_document" "assume" {
  statement {
    actions = ["sts:AssumeRole"]
    principals {
      type        = "Service"
      identifiers = ["states.amazonaws.com"]
    }
  }
}

resource "aws_iam_role" "sfn" {
  name               = "${var.name_prefix}-sfn-exec"
  assume_role_policy = data.aws_iam_policy_document.assume.json
  tags               = var.tags
}

data "aws_iam_policy_document" "sfn" {
  statement {
    sid       = "InvokeGlue"
    actions   = ["glue:StartJobRun", "glue:GetJobRun", "glue:GetJobRuns", "glue:BatchStopJobRun"]
    resources = length(var.task_role_arns) > 0 ? var.task_role_arns : ["*"]
  }
}

resource "aws_iam_role_policy" "sfn" {
  name   = "${var.name_prefix}-sfn"
  role   = aws_iam_role.sfn.id
  policy = data.aws_iam_policy_document.sfn.json
}

resource "aws_sfn_state_machine" "this" {
  name       = "${var.name_prefix}-workflow"
  role_arn   = aws_iam_role.sfn.arn
  definition = local.effective_definition
  tags       = var.tags
}

output "state_machine_arn" {
  value = aws_sfn_state_machine.this.arn
}

output "role_arn" {
  value = aws_iam_role.sfn.arn
}
