# Module: orchestrator-stepfunctions
# Serverless orchestration via a Step Functions state machine + a least-privilege role.
# The caller passes the state-machine definition and the task role ARNs it may invoke.

variable "name_prefix" {
  type = string
}

variable "tags" {
  type    = map(string)
  default = {}
}

variable "definition_json" {
  type        = string
  default     = ""
  description = "Amazon States Language JSON for the workflow. If empty, a starter workflow that runs the wired Glue jobs is generated."
}

variable "glue_job_names" {
  type        = list(string)
  default     = []
  description = "Glue job names to orchestrate. Used to generate the starter workflow when definition_json is empty."
}

variable "schedule_expression" {
  type        = string
  default     = ""
  description = "EventBridge schedule that starts the state machine, e.g. \"rate(1 day)\" or \"cron(0 3 * * ? *)\". Empty means no schedule: the pipeline is triggered by the operator or by an upstream event, which is a legitimate choice, so a cron is never invented."
}

variable "task_role_arns" {
  type        = list(string)
  default     = []
  description = "Resource ARNs the state machine may act on (e.g. Glue job ARNs)."
}

locals {
  # A real, runnable starter workflow: run the wired Glue jobs sequentially. The operator
  # can replace it by passing an explicit definition_json. Not a mock — it references the
  # actual job names wired from the compute module.
  #
  # Null-filtering matters: merge()-ing {Next} XOR {End} branches makes Terraform unify
  # the object types across the for-expression, emitting "Next": null / "End": null —
  # which the Step Functions CreateStateMachine schema validation rejects.
  generated_states = {
    for idx, name in var.glue_job_names : "Run_${idx}" => {
      for k, v in {
        Type       = "Task"
        Resource   = "arn:aws:states:::glue:startJobRun.sync"
        Parameters = { JobName = name }
        Next       = idx + 1 < length(var.glue_job_names) ? "Run_${idx + 1}" : null
        End        = idx + 1 < length(var.glue_job_names) ? null : true
      } : k => v if v != null
    }
  }
  effective_definition = var.definition_json != "" ? var.definition_json : jsonencode({
    Comment = "Starter workflow generated by MinusOps — runs the wired Glue ETL jobs in sequence."
    StartAt = length(var.glue_job_names) > 0 ? "Run_0" : "NoOp"
    States = merge(
      local.generated_states,
      {
        for k, v in { NoOp = { Type = "Pass", End = true } } : k => v
        if length(var.glue_job_names) == 0
      }
    )
  })
}

data "aws_iam_policy_document" "assume" {
  statement {
    actions = ["sts:AssumeRole"]
    principals {
      type        = "Service"
      identifiers = ["states.amazonaws.com"]
    }
  }
}

resource "aws_iam_role" "sfn" {
  name               = "${var.name_prefix}-sfn-exec"
  assume_role_policy = data.aws_iam_policy_document.assume.json
  tags               = var.tags
}

data "aws_iam_policy_document" "sfn" {
  statement {
    sid       = "InvokeGlue"
    actions   = ["glue:StartJobRun", "glue:GetJobRun", "glue:GetJobRuns", "glue:BatchStopJobRun"]
    resources = length(var.task_role_arns) > 0 ? var.task_role_arns : ["*"]
  }
}

resource "aws_iam_role_policy" "sfn" {
  name   = "${var.name_prefix}-sfn"
  role   = aws_iam_role.sfn.id
  policy = data.aws_iam_policy_document.sfn.json
}

resource "aws_sfn_state_machine" "this" {
  name       = "${var.name_prefix}-workflow"
  role_arn   = aws_iam_role.sfn.arn
  definition = local.effective_definition
  tags       = var.tags
}

# MINUS-111. Without this the state machine exists but nothing ever starts it -- the
# 2026-08-17 run had no automated trigger at all. Created only when the operator states a
# schedule, so an event-driven pipeline is not given a surprise cron.
resource "aws_cloudwatch_event_rule" "schedule" {
  count               = var.schedule_expression == "" ? 0 : 1
  name                = "${var.name_prefix}-workflow-schedule"
  description         = "Scheduled trigger for ${aws_sfn_state_machine.this.name}."
  schedule_expression = var.schedule_expression
  tags                = var.tags
}

# EventBridge assumes its own role to start the execution; it cannot reuse the state
# machine's role, whose trust policy names states.amazonaws.com.
data "aws_iam_policy_document" "events_assume" {
  statement {
    actions = ["sts:AssumeRole"]
    principals {
      type        = "Service"
      identifiers = ["events.amazonaws.com"]
    }
  }
}

resource "aws_iam_role" "events" {
  count              = var.schedule_expression == "" ? 0 : 1
  name               = "${var.name_prefix}-sfn-events"
  assume_role_policy = data.aws_iam_policy_document.events_assume.json
  tags               = var.tags
}

resource "aws_iam_role_policy" "events" {
  count = var.schedule_expression == "" ? 0 : 1
  name  = "${var.name_prefix}-sfn-events"
  role  = aws_iam_role.events[0].id
  policy = jsonencode({
    Version = "2012-10-17"
    Statement = [{
      Effect   = "Allow"
      Action   = "states:StartExecution"
      Resource = aws_sfn_state_machine.this.arn
    }]
  })
}

resource "aws_cloudwatch_event_target" "sfn" {
  count     = var.schedule_expression == "" ? 0 : 1
  rule      = aws_cloudwatch_event_rule.schedule[0].name
  target_id = "state-machine"
  arn       = aws_sfn_state_machine.this.arn
  role_arn  = aws_iam_role.events[0].arn
}

output "schedule_rule_name" {
  value = var.schedule_expression == "" ? "" : aws_cloudwatch_event_rule.schedule[0].name
}

output "state_machine_arn" {
  value = aws_sfn_state_machine.this.arn
}

output "role_arn" {
  value = aws_iam_role.sfn.arn
}
