"""
Starter small-file compaction job (PySpark on Glue) — generated by MinusOps.

Runnable skeleton, not a finished optimizer: for each configured prefix it reads the
Parquet files, coalesces them toward ~128 MB objects (the size Athena/Spark schedule
splits at), and rewrites the prefix. Replace TARGET_PREFIXES with your real hot
partitions, and prefer table-format-native compaction (Iceberg rewrite_data_files)
once a table format is adopted.

Grounded in AWS Athena performance guidance: many small files read 62-88% slower and
can throw S3 throttling errors; ~128 MB is the target object size.
"""
import sys

from awsglue.context import GlueContext
from awsglue.utils import getResolvedOptions
from pyspark.context import SparkContext

args = getResolvedOptions(sys.argv, ["JOB_NAME", "target_buckets"])

sc = SparkContext()
glue = GlueContext(sc)
spark = glue.spark_session

TARGET_OBJECT_MB = 128
# REVIEW: point at the prefixes that accumulate small files (e.g. streaming landings).
TARGET_PREFIXES = [f"s3://{b}/" for b in args["target_buckets"].split(",") if b]

for prefix in TARGET_PREFIXES:
    try:
        df = spark.read.parquet(prefix)
    except Exception as exc:  # empty/non-parquet prefixes are skipped, not fatal
        print(f"[compact] skip {prefix}: {exc}")
        continue
    approx_bytes = df.rdd.map(lambda r: len(str(r))).sum() if not df.isEmpty() else 0
    partitions = max(1, int(approx_bytes / (TARGET_OBJECT_MB * 1024 * 1024)) or 1)
    (df.repartition(partitions)
       .write.mode("overwrite")
       .parquet(prefix + "_compacted/"))
    print(f"[compact] {prefix} -> {partitions} file(s) at ~{TARGET_OBJECT_MB} MB "
          f"(review then swap _compacted/ into place)")

print("[compact] done")
