"""
Demo Terraform generator for cached fixture blueprints.

This module writes Terraform source only. It does not run terraform init, plan,
apply, or cloud CLI commands.
"""
import json
import os
import re
from pathlib import Path

import source_guard


def _safe_name(value):
    value = re.sub(r"[^a-zA-Z0-9-]+", "-", str(value).strip().lower()).strip("-")
    return value or "data-platform"


def _write(path, text):
    path = Path(path)
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(text.strip() + "\n", encoding="utf-8")


def generate(blueprint, inputs, terraform_dir):
    blueprint_id = blueprint["id"]
    if blueprint_id != "aws-data-pipeline-standard":
        raise ValueError(f"unsupported demo blueprint: {blueprint_id}")
    return generate_aws_data_pipeline(inputs, terraform_dir)


def generate_aws_data_pipeline(inputs, terraform_dir):
    out = Path(terraform_dir)
    out.mkdir(parents=True, exist_ok=True)
    env = _safe_name(inputs.get("environment", "dev"))
    owner = _safe_name(inputs["owner"])
    region = inputs.get("region", "us-east-1")
    daily_data_gb = float(inputs["daily_data_gb"])
    ingestion_mode = inputs.get("ingestion_mode", "batch")
    prefix = f"{owner}-{env}-pipeline"

    files = {
        "main.tf": f'''
# Generated by MinusTerraformCli.
# Terraform loads every .tf file in this directory.
locals {{
  name_prefix   = "{prefix}"
  environment   = var.environment
  owner         = var.owner
  daily_data_gb = var.daily_data_gb
  common_tags = {{
    Environment = var.environment
    Owner       = var.owner
    ManagedBy   = "MinusTerraformCli"
    DemoFixture = "aws-data-pipeline-standard"
  }}
}}
''',
        "provider.tf": '''
terraform {
  required_version = ">= 1.5.0"
  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = "~> 5.0"
    }
  }
}

provider "aws" {
  region = var.region
  default_tags {
    tags = local.common_tags
  }
}

data "aws_caller_identity" "current" {}
data "aws_partition" "current" {}
''',
        "variables.tf": f'''
variable "region" {{
  type    = string
  default = "{region}"
}}

variable "environment" {{
  type    = string
  default = "{env}"
}}

variable "owner" {{
  type    = string
  default = "{owner}"
}}

variable "ingestion_mode" {{
  type    = string
  default = "{ingestion_mode}"
}}

variable "daily_data_gb" {{
  type    = number
  default = {daily_data_gb:g}
}}
''',
        "kms.tf": '''
resource "aws_kms_key" "pipeline" {
  description             = "KMS key for governed data pipeline storage and query results"
  deletion_window_in_days = 7
  enable_key_rotation     = true
}

resource "aws_kms_alias" "pipeline" {
  name          = "alias/${local.name_prefix}"
  target_key_id = aws_kms_key.pipeline.key_id
}
''',
        "s3.tf": '''
locals {
  bucket_names = {
    bronze         = "${local.name_prefix}-bronze-${data.aws_caller_identity.current.account_id}"
    silver         = "${local.name_prefix}-silver-${data.aws_caller_identity.current.account_id}"
    gold           = "${local.name_prefix}-gold-${data.aws_caller_identity.current.account_id}"
    athena_results = "${local.name_prefix}-athena-results-${data.aws_caller_identity.current.account_id}"
  }
}

resource "aws_s3_bucket" "zone" {
  for_each = local.bucket_names
  bucket   = each.value
}

resource "aws_s3_bucket_public_access_block" "zone" {
  for_each                = aws_s3_bucket.zone
  bucket                  = each.value.id
  block_public_acls       = true
  block_public_policy     = true
  ignore_public_acls      = true
  restrict_public_buckets = true
}

resource "aws_s3_bucket_server_side_encryption_configuration" "zone" {
  for_each = aws_s3_bucket.zone
  bucket   = each.value.id
  rule {
    apply_server_side_encryption_by_default {
      kms_master_key_id = aws_kms_key.pipeline.arn
      sse_algorithm     = "aws:kms"
    }
  }
}

resource "aws_s3_bucket_versioning" "zone" {
  for_each = aws_s3_bucket.zone
  bucket   = each.value.id
  versioning_configuration {
    status = "Enabled"
  }
}

resource "aws_s3_bucket_lifecycle_configuration" "zone" {
  for_each = aws_s3_bucket.zone
  bucket   = each.value.id
  rule {
    id     = "standard-retention"
    status = "Enabled"
    filter {}
    noncurrent_version_expiration {
      noncurrent_days = 30
    }
  }
}
''',
        "iam.tf": '''
data "aws_iam_policy_document" "glue_assume" {
  statement {
    actions = ["sts:AssumeRole"]
    principals {
      type        = "Service"
      identifiers = ["glue.amazonaws.com"]
    }
  }
}

resource "aws_iam_role" "glue_role" {
  name               = "${local.name_prefix}-glue-role"
  assume_role_policy = data.aws_iam_policy_document.glue_assume.json
}

resource "aws_iam_role_policy" "glue_policy" {
  name = "${local.name_prefix}-glue-policy"
  role = aws_iam_role.glue_role.id
  policy = jsonencode({
    Version = "2012-10-17"
    Statement = [
      {
        Effect = "Allow"
        Action = ["s3:GetObject", "s3:PutObject", "s3:ListBucket"]
        Resource = concat([for b in aws_s3_bucket.zone : b.arn], [for b in aws_s3_bucket.zone : "${b.arn}/*"])
      },
      {
        Effect   = "Allow"
        Action   = ["kms:Decrypt", "kms:Encrypt", "kms:GenerateDataKey"]
        Resource = [aws_kms_key.pipeline.arn]
      },
      {
        Effect   = "Allow"
        Action   = ["logs:CreateLogGroup", "logs:CreateLogStream", "logs:PutLogEvents"]
        Resource = ["arn:${data.aws_partition.current.partition}:logs:${var.region}:${data.aws_caller_identity.current.account_id}:log-group:/aws-glue/*"]
      }
    ]
  })
}

data "aws_iam_policy_document" "sfn_assume" {
  statement {
    actions = ["sts:AssumeRole"]
    principals {
      type        = "Service"
      identifiers = ["states.amazonaws.com"]
    }
  }
}

resource "aws_iam_role" "sfn_role" {
  name               = "${local.name_prefix}-sfn-role"
  assume_role_policy = data.aws_iam_policy_document.sfn_assume.json
}

resource "aws_iam_role_policy" "sfn_policy" {
  name = "${local.name_prefix}-sfn-policy"
  role = aws_iam_role.sfn_role.id
  policy = jsonencode({
    Version = "2012-10-17"
    Statement = [{
      Effect   = "Allow"
      Action   = ["glue:StartJobRun", "glue:GetJobRun", "glue:GetJobRuns"]
      Resource = [aws_glue_job.bronze_to_silver.arn, aws_glue_job.silver_to_gold.arn]
    }]
  })
}
''',
        "glue.tf": '''
resource "aws_glue_catalog_database" "pipeline" {
  name = replace("${local.name_prefix}-catalog", "-", "_")
}

resource "aws_glue_job" "bronze_to_silver" {
  name     = "${local.name_prefix}-bronze-to-silver"
  role_arn = aws_iam_role.glue_role.arn
  command {
    script_location = "s3://${aws_s3_bucket.zone["bronze"].bucket}/scripts/bronze_to_silver.py"
    python_version  = "3"
  }
  glue_version      = "4.0"
  number_of_workers = 2
  worker_type       = "G.1X"
}

resource "aws_glue_job" "silver_to_gold" {
  name     = "${local.name_prefix}-silver-to-gold"
  role_arn = aws_iam_role.glue_role.arn
  command {
    script_location = "s3://${aws_s3_bucket.zone["bronze"].bucket}/scripts/silver_to_gold.py"
    python_version  = "3"
  }
  glue_version      = "4.0"
  number_of_workers = 2
  worker_type       = "G.1X"
}
''',
        "scripts.tf": '''
resource "aws_s3_object" "bronze_to_silver_script" {
  bucket                 = aws_s3_bucket.zone["bronze"].bucket
  key                    = "scripts/bronze_to_silver.py"
  source                 = "${path.module}/scripts/glue/bronze_to_silver.py"
  server_side_encryption = "aws:kms"
  kms_key_id             = aws_kms_key.pipeline.arn
}

resource "aws_s3_object" "silver_to_gold_script" {
  bucket                 = aws_s3_bucket.zone["bronze"].bucket
  key                    = "scripts/silver_to_gold.py"
  source                 = "${path.module}/scripts/glue/silver_to_gold.py"
  server_side_encryption = "aws:kms"
  kms_key_id             = aws_kms_key.pipeline.arn
}
''',
        "step_functions.tf": '''
resource "aws_sfn_state_machine" "pipeline" {
  name     = "${local.name_prefix}-workflow"
  role_arn = aws_iam_role.sfn_role.arn
  definition = jsonencode({
    StartAt = "BronzeToSilver"
    States = {
      BronzeToSilver = {
        Type     = "Task"
        Resource = "arn:aws:states:::glue:startJobRun.sync"
        Parameters = { JobName = aws_glue_job.bronze_to_silver.name }
        Next = "SilverToGold"
      }
      SilverToGold = {
        Type     = "Task"
        Resource = "arn:aws:states:::glue:startJobRun.sync"
        Parameters = { JobName = aws_glue_job.silver_to_gold.name }
        End = true
      }
    }
  })
}
''',
        "athena.tf": '''
resource "aws_athena_workgroup" "pipeline" {
  name = "${local.name_prefix}-workgroup"
  configuration {
    enforce_workgroup_configuration = true
    result_configuration {
      output_location = "s3://${aws_s3_bucket.zone["athena_results"].bucket}/"
      encryption_configuration {
        encryption_option = "SSE_KMS"
        kms_key_arn       = aws_kms_key.pipeline.arn
      }
    }
  }
}
''',
        "monitoring.tf": '''
resource "aws_cloudwatch_metric_alarm" "sfn_failures" {
  alarm_name          = "${local.name_prefix}-sfn-failures"
  comparison_operator = "GreaterThanThreshold"
  evaluation_periods  = 1
  metric_name         = "ExecutionsFailed"
  namespace           = "AWS/States"
  period              = 300
  statistic           = "Sum"
  threshold           = 0
  dimensions = {
    StateMachineArn = aws_sfn_state_machine.pipeline.arn
  }
}

resource "aws_budgets_budget" "monthly" {
  name         = "${local.name_prefix}-monthly-budget"
  budget_type  = "COST"
  limit_amount = max(100, var.daily_data_gb * 4)
  limit_unit   = "USD"
  time_unit    = "MONTHLY"
}
''',
        "outputs.tf": '''
output "bronze_bucket" { value = aws_s3_bucket.zone["bronze"].bucket }
output "silver_bucket" { value = aws_s3_bucket.zone["silver"].bucket }
output "gold_bucket" { value = aws_s3_bucket.zone["gold"].bucket }
output "kms_key_arn" { value = aws_kms_key.pipeline.arn }
output "step_function_arn" { value = aws_sfn_state_machine.pipeline.arn }
''',
        "README.md": f'''
# {prefix}

Generated Terraform for demo fixture `aws-data-pipeline-standard`.

Safe workflow:

```powershell
python core/plan_gate.py verify --dir {out.as_posix()}
python core/plan_gate.py plan --dir {out.as_posix()}
```

Do not run apply until the plan hash is reviewed and approved.
''',
    }
    scripts = {
        "scripts/glue/bronze_to_silver.py": "print('bronze to silver placeholder')\n",
        "scripts/glue/silver_to_gold.py": "print('silver to gold placeholder')\n",
    }
    for name, text in files.items():
        _write(out / name, text)
    for name, text in scripts.items():
        _write(out / name, text)
    manifest = {
        "blueprint": "aws-data-pipeline-standard",
        "terraform_dir": str(out),
        "inputs": inputs,
        "files": sorted(list(files) + list(scripts)),
    }
    _write(out / "minus-generated.json", json.dumps(manifest, indent=2))
    source_guard.write_baseline(out, label="generated", extra={"demo_fixture": "aws-data-pipeline-standard"})
    return manifest
