"""
CLI session state: which run is the operator working on right now?

Without this, every command carries `--dir runs/<id>/terraform`, which is the single
most-typed and most-mistyped argument in the tool. `minusctl use <run-id>` records the
selection in `.minus/context.json` and every later command defaults to it.

That makes this file a piece of state that decides WHICH INFRASTRUCTURE a later `gate apply`
touches, so every failure mode here is loud on purpose:

  * A corrupt context file raises. Silently falling back to "the newest run" would point an
    apply at different infrastructure than the operator selected, and say nothing.
  * An active run whose directory has been deleted raises for the same reason.
  * No context file at all returns None -- there is genuinely no selection, and inventing one
    from `latest_run()` is the same guess wearing a different hat.
  * A run id containing a path separator or `..` is refused before it is stored, because it
    is read back off disk later and joined into a path.

Writes go through a temp file plus `os.replace` (NFR-04): a half-written context.json is
unparseable, and "delete the file" is not an obvious recovery to anyone who did not write it.

Depends on: core/reporting/runs.py (for resolution), stdlib only otherwise
Shells out to: nothing
Used by: core/cli/main.py, every module under core/cli/commands/
"""
import json
import os
import re
import tempfile

import runs

WORKSPACE = os.getcwd()
CONTEXT_DIR = ".minus"
CONTEXT_FILE = "context.json"

# Run ids are generated by runs.py from slugged parts, so this is the shape they already
# have. Enforced here because the value is read back from a file and joined into a path.
_RUN_ID_RE = re.compile(r"^[A-Za-z0-9][A-Za-z0-9._-]*$")


class ContextError(RuntimeError):
    """The recorded context cannot be trusted to name the run the operator meant."""


def context_path():
    return os.path.join(WORKSPACE, CONTEXT_DIR, CONTEXT_FILE)


def _validate(run_id):
    if not run_id or not _RUN_ID_RE.match(run_id):
        raise ContextError(
            f"{run_id!r} is not a valid run id -- it is joined into a filesystem path, so "
            "separators and `..` are refused")
    return run_id


def read():
    """Raw context document, or {} when none has been written."""
    path = context_path()
    if not os.path.exists(path):
        return {}
    try:
        with open(path, encoding="utf-8") as f:
            data = json.load(f)
    except (OSError, ValueError) as exc:
        raise ContextError(
            f"{path} is unreadable ({exc}). Fix or delete it, then re-run `minusctl use "
            "<run-id>` -- guessing which run you meant is how an apply lands on the wrong "
            "stack.")
    if not isinstance(data, dict):
        raise ContextError(f"{path} is not a JSON object")
    return data


def set_active_run(run_id):
    """Record the active run. Returns the resolved run record."""
    _validate(run_id)
    record = runs.get_run(run_id)
    if not record:
        raise ContextError(f"no run matches {run_id!r}; `minusctl runs list` shows what exists")

    document = dict(read())
    document["active_run"] = record["run_id"]
    _atomic_write(context_path(), json.dumps(document, indent=2) + "\n")
    return record


def clear():
    path = context_path()
    if os.path.exists(path):
        os.unlink(path)


def active_run_id():
    return read().get("active_run")


def active_run():
    """The active run record, or None when nothing is selected.

    Raises rather than returning None when a selection EXISTS but cannot be resolved: those
    are different situations and only one of them is safe to paper over."""
    run_id = active_run_id()
    if not run_id:
        return None
    _validate(run_id)
    record = runs.get_run(run_id)
    if not record:
        raise ContextError(
            f"the active run {run_id!r} is no longer on disk. Run `minusctl use <run-id>` to "
            "select another, or `minusctl runs list` to see what is left.")
    return record


def resolve_run(run_id=None):
    """Explicit id wins, then the active run. Never falls through to "the newest one"."""
    if run_id and run_id != "latest":
        record = runs.get_run(run_id)
        if not record:
            raise ContextError(f"no run matches {run_id!r}")
        return record
    if run_id == "latest":
        return runs.latest_run()
    record = active_run()
    if not record:
        raise ContextError(
            "no run selected and none given. Run `minusctl use <run-id>` first, or pass "
            "--run <run-id>.")
    return record


def _atomic_write(path, text):
    directory = os.path.dirname(path)
    os.makedirs(directory, exist_ok=True)
    fd, tmp = tempfile.mkstemp(dir=directory, prefix=".", suffix=".tmp")
    try:
        with os.fdopen(fd, "w", encoding="utf-8", newline="\n") as f:
            f.write(text)
        os.replace(tmp, path)
    except BaseException:
        try:
            os.unlink(tmp)
        except OSError:
            pass
        raise
