"""
Starter AWS Glue (PySpark) ETL job — generated by MinusOps.

This is a runnable skeleton, not a finished pipeline. It reads from a source path,
applies a no-op passthrough transform, and writes Parquet to a target path. Replace the
transform with your real validate/clean/normalize logic, and wire real job arguments
(--source_path, --target_path) via the Glue job's DefaultArguments before production use.

Grounded in the medallion pattern (raw -> cleaned -> curated) and Well-Architected
Performance guidance: write columnar Parquet, partitioned, to avoid the small-files problem.
"""
import sys

from awsglue.context import GlueContext
from awsglue.utils import getResolvedOptions
from pyspark.context import SparkContext

# --source_path / --target_path are supplied as Glue job arguments (REVIEW: set before run).
_args = getResolvedOptions(sys.argv, ["JOB_NAME"])
_optional = {}
for _key in ("source_path", "target_path"):
    try:
        _optional.update(getResolvedOptions(sys.argv, [_key]))
    except Exception:
        _optional[_key] = ""

sc = SparkContext()
glue = GlueContext(sc)
spark = glue.spark_session

source_path = _optional.get("source_path") or ""
target_path = _optional.get("target_path") or ""

if not source_path or not target_path:
    # Fail loudly rather than silently no-op: the job must be wired before it does work.
    raise SystemExit(
        "REVIEW: set --source_path and --target_path Glue job arguments before running this ETL job."
    )

df = spark.read.parquet(source_path) if source_path.endswith("/") else spark.read.json(source_path)

# TODO(operator): replace with real validation / cleaning / normalization / enrichment.
transformed = df

# Columnar, partition-friendly write (tune partitionBy to your query patterns).
transformed.write.mode("overwrite").parquet(target_path)
